name: Automated Preprocessing

on:
  push:
    branches: [main]
    paths:
      - "dataset-stroke-data.csv"
      - "preprocessing/automate_Alief_Athallah.py"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas numpy scikit-learn joblib

      - name: Run preprocessing script
        run: python preprocessing/automate_Alief_Athallah.py

      - name: Upload imputer
        uses: actions/upload-artifact@v4
        with:
          name: imputer
          path: preprocessing/stroke_preprocessing/imputer.pkl

      - name: Upload label encoders
        uses: actions/upload-artifact@v4
        with:
          name: label_encoders
          path: preprocessing/stroke_preprocessing/label_encoders.pkl

      - name: Upload preprocessor (scaler)
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor
          path: preprocessing/stroke_preprocessing/preprocessor.pkl

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: stroke_preprocessed
          path: preprocessing/stroke_preprocessing/stroke_preprocessed.csv
